name: CI

on:
  pull_request:
  push:
    branches: [ master ]


jobs:
  test_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: run tests macos
        run: CC=clang make test
  test_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: run tests ubuntu
        run: CC=gcc make test
